name: Pre-commit Hook

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.draft != true }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python (required for pre-commit)
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install pre-commit and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pre-commit install

      - name: Run pre-commit hooks
        run: |
          pre-commit run --all-files
